language: node_js
node_js:
  - "node"
  - "12"
  - "10"
  - "8"
before_install: curl -L https://unpkg.com/@pnpm/self-installer | node
install: pnpm install
script: pnpm run ci
after_success: pnpm run coverage
